name:                haskell-avatar-maker
version:             0.1.0.0
github:              "hmqyu/haskell-avatar-maker"
license:             BSD3
author:              "Helen (Meiqi) Yu"
maintainer:          "helenmqyu@gmail.com"
copyright:           "2023 Helen (Meiqi) Yu"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/hmqyu/haskell-avatar-maker#readme>

dependencies:
- base >= 4.7 && < 5
- JuicyPixels
- gloss
- gloss-juicy

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  dependencies:
    - Cabal
    - JuicyPixels

executables:
  haskell-avatar-maker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-avatar-maker
    - JuicyPixels

# tests:
#   haskell-avatar-maker-test:
#     main:                Spec.hs
#     source-dirs:         test
#     ghc-options:
#     - -threaded
#     - -rtsopts
#     - -with-rtsopts=-N
#     dependencies:
#     - haskell-avatar-maker
#     - JuicyPixels
